import java.util.*;

public class ExceptionDemo {
    public static void main(String[] args) {
        int a = 0, b = 0, c;
        Scanner in = new Scanner(System.in);

        System.out.print("\nPLEASE ENTER TWO NUMBERS FOR DIVISION: ");
        try {
            a = in.nextInt();
            b = in.nextInt();
            System.out.println("I AM IN TRY BLOCK 1");
            c = a / b;
            System.out.println("\nDIVISION OF TWO NUMBERS IS: " + c);
        } catch (InputMismatchException e) {
            System.out.println("\nI AM IN CATCH BLOCK 1");
            System.out.println("CHECK INPUT");
            System.out.println(e);
        } catch (ArithmeticException e) {
            System.out.println("\nI AM IN CATCH BLOCK 1");
            System.out.println("DIVISION BY ZERO IS NOT POSSIBLE");
            System.out.println(e);
        }

        System.out.println("\nEND OF ARITHMETIC EXCEPTION CONCEPT");
    }
}
